/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lancadornotas.view;

import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.lancadornotas.model.Aluno;
import com.mycompany.lancadornotas.model.Nota;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexisdanielkang
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
    
    //Aluno
    private List<Aluno> listaAlunos =  new ArrayList<>();   //Lista de alunos
    private int posicaoTabelaAluno = -1;                    //Variavel criada onde irá armazenar a posição do objeto que queremos remover da lista
    
    //Nota
    private List<Nota> listaNotas = new ArrayList<>();      //Lista de notas
    private int posicaoTabelaNota = -1;                     //Variavel criada onde irá armazenar a posição do objeto que queremos remover da lista
    
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);        //Centraliza a tela
        setResizable(false);                //Não permite maximixar a tela
        btnDeletarAluno.setEnabled(false);  //Deixa indisponível o botão Deletar(Aluno)
        btnDeletarNota.setEnabled(false);   //Deixa indisponível o botão Deletar(Nota)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cbxTurma = new javax.swing.JComboBox<>();
        ftdDAta = new javax.swing.JFormattedTextField();
        btnSalvarAluno = new javax.swing.JButton();
        btnLimparAluno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        btnDeletarAluno = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxAluno = new javax.swing.JComboBox<>();
        cbxDisciplina = new javax.swing.JComboBox<>();
        txtNota = new javax.swing.JTextField();
        btnLimparNota = new javax.swing.JButton();
        btnSalvarNota = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        btnDeletarNota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Turma");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Data nasc:");

        txtNome.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        cbxTurma.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cbxTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "1A", "1B", "2A", "2B", "3A", "3B" }));

        try {
            ftdDAta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftdDAta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        btnSalvarAluno.setBackground(new java.awt.Color(51, 153, 255));
        btnSalvarAluno.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSalvarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarAluno.setIcon(new javax.swing.ImageIcon("/Users/alexisdanielkang/NetBeansProjects/LancadorNotas/src/main/resources/salvar.png")); // NOI18N
        btnSalvarAluno.setText("Salvar");
        btnSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlunoActionPerformed(evt);
            }
        });

        btnLimparAluno.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnLimparAluno.setIcon(new javax.swing.ImageIcon("/Users/alexisdanielkang/NetBeansProjects/LancadorNotas/src/main/resources/limpar-limpo.png")); // NOI18N
        btnLimparAluno.setText("Limpar");
        btnLimparAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparAlunoActionPerformed(evt);
            }
        });

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Turma", "Idade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlunos);

        btnDeletarAluno.setBackground(new java.awt.Color(255, 51, 51));
        btnDeletarAluno.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnDeletarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletarAluno.setText("Deletar");
        btnDeletarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ftdDAta, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxTurma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvarAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimparAluno)
                                .addGap(9, 9, 9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeletarAluno)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftdDAta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarAluno)
                    .addComponent(btnLimparAluno))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletarAluno)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alunos", new javax.swing.ImageIcon("/Users/alexisdanielkang/NetBeansProjects/LancadorNotas/src/main/resources/graduating-student.png"), jPanel1); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setText("Aluno:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setText("Disciplina:");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel7.setText("Nota:");

        cbxAluno.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        cbxDisciplina.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        cbxDisciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Portugues", "Matematica", "Ingles", "Ciencia", "Historia", "Geografia" }));

        txtNota.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        btnLimparNota.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnLimparNota.setIcon(new javax.swing.ImageIcon("/Users/alexisdanielkang/NetBeansProjects/LancadorNotas/src/main/resources/limpar-limpo.png")); // NOI18N
        btnLimparNota.setText("Limpar");
        btnLimparNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparNotaActionPerformed(evt);
            }
        });

        btnSalvarNota.setBackground(new java.awt.Color(51, 153, 255));
        btnSalvarNota.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSalvarNota.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarNota.setIcon(new javax.swing.ImageIcon("/Users/alexisdanielkang/NetBeansProjects/LancadorNotas/src/main/resources/salvar.png")); // NOI18N
        btnSalvarNota.setText("Salvar");
        btnSalvarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNotaActionPerformed(evt);
            }
        });

        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aluno", "Disciplina", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNotasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNotas);

        btnDeletarNota.setBackground(new java.awt.Color(255, 51, 0));
        btnDeletarNota.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnDeletarNota.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletarNota.setText("Deletar");
        btnDeletarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxDisciplina, 0, 347, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeletarNota)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSalvarNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparNota))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparNota)
                    .addComponent(btnSalvarNota))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeletarNota)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Notas", new javax.swing.ImageIcon("/Users/alexisdanielkang/NetBeansProjects/LancadorNotas/src/main/resources/notas-adesivas.png"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparAlunoActionPerformed
        //Chama a função que reseta os componentes
        resetarCamposAluno();
    }//GEN-LAST:event_btnLimparAlunoActionPerformed

    private void btnSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlunoActionPerformed
        listaAlunos.add(retornaAluno());    //Estamos adicionando um novo objeto (Aluno) utilizando a nossa função que retorna um objeto
        resetarCamposAluno();               //Reseta os campos
        atualizarTabelaAlunos();            //Atualiza a tabela de alunos
        atualizarComboAlunos();             //Atualiza a combobox de alunos
    }//GEN-LAST:event_btnSalvarAlunoActionPerformed
    
    //Evento criado ao clicar na tabela
    private void tblAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlunosMouseClicked
        posicaoTabelaAluno = tblAlunos.getSelectedRow();    //Quando usuário clica na linha ela retorna uma posição que armazenamos nesta variável global
        btnDeletarAluno.setEnabled(true);                   //Habilita o botão Deletar(Aluno)
    }//GEN-LAST:event_tblAlunosMouseClicked

    private void btnDeletarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarAlunoActionPerformed
        listaAlunos.remove(posicaoTabelaAluno); //Remove da lista o aluno a partir da posição que foi pega após o usuário clicar na tabela
        atualizarTabelaAlunos();                //Atualiza a tabela Alunos
        posicaoTabelaAluno = -1;                //Resetamos a variável para nao manter a posição salva após remover o objeto da lista
        btnDeletarAluno.setEnabled(false);      //Desabilita o botão
        atualizarComboAlunos();                 //Atualiza combobox aluno
    }//GEN-LAST:event_btnDeletarAlunoActionPerformed

    private void btnLimparNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparNotaActionPerformed
        //Reseta e limpa os campos
        resetarCamposNota();
    }//GEN-LAST:event_btnLimparNotaActionPerformed

    private void btnSalvarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNotaActionPerformed
        
        listaNotas.add(retornaNota());  //Adicionamos um novo objeto na lista usando uma função que retorna um objeto (Nota)
        resetarCamposNota();            //Reseta e limpa os campos notas
        atualizarTabelaNotas();         //Atualiza a tabela notas
        
    }//GEN-LAST:event_btnSalvarNotaActionPerformed

    //Evento que pega 
    private void tblNotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNotasMouseClicked
        posicaoTabelaNota =  tblNotas.getSelectedRow(); //Pega a posição da tabela e armazena em uma variável
        btnDeletarNota.setEnabled(true);                //Habilita o botão deletar (Nota)
    }//GEN-LAST:event_tblNotasMouseClicked

    private void btnDeletarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarNotaActionPerformed
        listaNotas.remove(posicaoTabelaNota);   // Remove o objeto da lista a partir da posição que foi armazena ao clicar na tabela
        atualizarTabelaNotas();                 // Atualiza a tabela notas
        posicaoTabelaNota = -1;                 // reseta a posição
        btnDeletarNota.setEnabled(false);       // Desabilita o botão deletar(Nota)
    }//GEN-LAST:event_btnDeletarNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletarAluno;
    private javax.swing.JButton btnDeletarNota;
    private javax.swing.JButton btnLimparAluno;
    private javax.swing.JButton btnLimparNota;
    private javax.swing.JButton btnSalvarAluno;
    private javax.swing.JButton btnSalvarNota;
    private javax.swing.JComboBox<Object> cbxAluno;
    private javax.swing.JComboBox<String> cbxDisciplina;
    private javax.swing.JComboBox<String> cbxTurma;
    private javax.swing.JFormattedTextField ftdDAta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JTable tblNotas;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables

    private void resetarCamposAluno() {
        txtNome.setText("");            //Limpa o campo
        cbxTurma.setSelectedIndex(0);   //Deixa setado o primeiro elemento da combobox
        ftdDAta.setText("");            //Limpa o campo
        posicaoTabelaAluno = -1;        //Reseta a posição
    }
    
    //Função criada para retornar um objeto do tipo Aluno
    private Aluno retornaAluno(){
        String nome = txtNome.getText();                        //Armazena em uma variável o que foi digitado pelo usuário no campo do nome
        String turma = cbxTurma.getSelectedItem().toString();   //Armazena o que foi selecionado na combobox e o ".toString" pega o que foi seleciona e retorna tipo String 
        
        DateTimeFormatter formatter = 
                DateTimeFormatter.ofPattern("dd/MM/yyyy");      //Formata a data para dia/mes/ano   
        
        String data = ftdDAta.getText();                        //Armazena o texto da data digitada em uma string
        
        LocalDate dataNasc = LocalDate.parse(data, formatter);  //Transforma a data para LocalDate com a formatação desejada
        
        //Forma 1 para retornar Aluno
        return new Aluno(nome, turma, dataNasc);                //Retorna um aluno passando diretamente a instancia
        
        /* Forma 2 
            Aluno a =  new Aluno();
            a.setNome(nome);
            a.setTurma(turma);
            a.setDataNasc(dataNasc);
            
            return a;
        */
        
        /* Forma 3
            Aluno a =  new Aluno(nome, turma, dataNasc);
            return a;
        */
        
    }
    
    
    /*
    * Atualiza a tabela de alunos exibida na interface.
    * Remove todas as linhas atuais e adiciona novamente
    * os dados presentes na lista de alunos.
    */
    private void atualizarTabelaAlunos() {

        // Obtém o modelo de dados associado à JTable
        DefaultTableModel modelo =
               (DefaultTableModel) tblAlunos.getModel();

        // Remove todas as linhas existentes da tabela
        modelo.setRowCount(0);

        // Percorre todos os alunos da lista
        for (Aluno a : listaAlunos) {

            // Adiciona uma nova linha na tabela com os dados do aluno
            modelo.addRow(new Object[]{
                a.getId(),          // Coluna ID
                a.getNome(),        // Coluna Nome
                a.getTurma(),       // Coluna Turma
                a.retornaIdade()    // Coluna Idade
            });
        }

        // Notifica a tabela de que os dados foram alterados,
        // forçando a atualização da interface gráfica
        modelo.fireTableDataChanged();
    }
    
    /**
     * Atualiza os itens do JComboBox de alunos.
     * Remove os itens atuais e carrega novamente
     * os alunos presentes na lista.
    */
    private void atualizarComboAlunos() {

        // Remove todos os itens atualmente exibidos no JComboBox
        cbxAluno.removeAllItems();

        // Adiciona a opção padrão para o usuário selecionar
        cbxAluno.addItem("Selecione...");

        // Percorre a lista de alunos
        for (Aluno a : listaAlunos) {
            // Adiciona cada aluno como uma opção do JComboBox
            cbxAluno.addItem(a);
        }
    }

    /**
    * Limpa os campos do formulário de notas,
    * retornando-os ao estado inicial.
    */
    private void resetarCamposNota() {

        // Seleciona a primeira opção do combo de alunos ("Selecione...")
        cbxAluno.setSelectedIndex(0);

        // Seleciona a primeira opção do combo de disciplinas
        cbxDisciplina.setSelectedIndex(0);

        // Limpa o campo de texto da nota
        txtNota.setText("");

        // Reseta a posição da linha selecionada na tabela
        // (-1 indica que nenhuma linha está selecionada)
        posicaoTabelaNota = -1;
    }
    
    /**
    * Cria e retorna um objeto Nota com os dados
    * informados nos campos da interface.
    */
    private Nota retornaNota() {

        // Obtém o aluno selecionado no JComboBox
        Aluno a = (Aluno) cbxAluno.getSelectedItem();

        // Obtém a disciplina selecionada no JComboBox
        String disciplina =
                (String) cbxDisciplina.getSelectedItem();

        // Converte o texto digitado para o tipo float
        float nota = Float.parseFloat(txtNota.getText());

        // Cria um novo objeto Nota
        Nota n = new Nota();

        // Define o aluno da nota
        n.setAluno(a);

        // Define a disciplina da nota
        n.setDisciplina(disciplina);

        // Define o valor da nota
        n.setNota(nota);

        // Retorna o objeto Nota preenchido
        return n;
    }
    
    /**
    * Atualiza a tabela de notas exibida na interface.
    * Remove todas as linhas atuais e carrega novamente
    * os dados presentes na lista de notas.
    */
    private void atualizarTabelaNotas() {

        // Obtém o modelo de dados associado à JTable de notas
        DefaultTableModel modelo =
                (DefaultTableModel) tblNotas.getModel();

        // Remove todas as linhas existentes da tabela
        modelo.setRowCount(0);

        // Percorre todas as notas cadastradas na lista
        for (Nota n : listaNotas) {

            // Adiciona uma nova linha na tabela com os dados da nota
            modelo.addRow(new Object[]{
                n.getAluno(),          // Aluno relacionado à nota
                n.getDisciplina(),     // Disciplina da nota
                n.retornaSituacao()    // Situação do aluno (Aprovado/Reprovado, por exemplo)
            });
        }

        // Notifica a tabela que os dados foram alterados
        // para atualizar a exibição na interface
        modelo.fireTableDataChanged();
    }
}
